# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aGpsEX9awebvhSlQPcL8lhZ26dm4Xpl
"""

print("Hello World")