# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jINgyXSnK9-5lDF8higauzJOxPq0UvS
"""

list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

print("Output:", end=" ")
for num in list1:
    if num > 0:
        print(num, end=", ")
print("\b\b")

positive_list = []
for num in list2:
    if num > 0:
        positive_list.append(num)

print("Output:", positive_list)